"""Add validation_rules column to challenges

Revision ID: 8b9f8b9c4683
Revises: 004
Create Date: 2025-12-24 20:26:58.368186

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8b9f8b9c4683"
down_revision: Union[str, None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stripe_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("event_data", sa.JSON(), nullable=False),
        sa.Column("stripe_created", sa.DateTime(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_event_id"),
    )
    op.create_table(
        "certificates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("achievement_data", sa.JSON(), nullable=False),
        sa.Column("certificate_number", sa.String(length=50), nullable=False),
        sa.Column("verification_code", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("pdf_path", sa.String(length=500), nullable=True),
        sa.Column("pdf_size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "earned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("template_version", sa.String(length=20), nullable=False),
        sa.Column("issuer", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("certificate_number"),
        sa.UniqueConstraint("verification_code"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("access_token_hash", sa.String(length=255), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=255), nullable=False),
        sa.Column("device_info", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_used",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_price_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("tier", sa.String(length=50), nullable=False),
        sa.Column("current_period_start", sa.DateTime(), nullable=False),
        sa.Column("current_period_end", sa.DateTime(), nullable=False),
        sa.Column("interval", sa.String(length=10), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("canceled_at", sa.DateTime(), nullable=True),
        sa.Column("subscription_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_subscription_id"),
    )
    op.create_table(
        "token_usage",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("model", sa.String(length=20), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", "model", name="unique_user_date_model"),
    )
    op.create_table(
        "user_progress",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=False),
        sa.Column("challenges_completed", sa.Integer(), nullable=False),
        sa.Column("challenges_attempted", sa.Integer(), nullable=False),
        sa.Column("web_track_completed", sa.Integer(), nullable=False),
        sa.Column("data_track_completed", sa.Integer(), nullable=False),
        sa.Column("cloud_track_completed", sa.Integer(), nullable=False),
        sa.Column("ai_requests_total", sa.Integer(), nullable=False),
        sa.Column("ai_tier_unlocked", sa.String(length=20), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("longest_streak", sa.Integer(), nullable=False),
        sa.Column("last_activity", sa.DateTime(timezone=True), nullable=True),
        sa.Column("achievements", sa.JSON(), nullable=True),
        sa.Column("badges", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "conversation_messages",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("model_used", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant', 'system')", name="valid_message_role"
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_invoice_id", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("payment_method", sa.String(length=100), nullable=True),
        sa.Column("last4", sa.String(length=4), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("subscription_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_payment_intent_id"),
    )
    op.create_table(
        "test_results",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("test_name", sa.String(length=200), nullable=False),
        sa.Column("test_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("execution_time", sa.Integer(), nullable=True),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("expected_output", sa.Text(), nullable=True),
        sa.Column("actual_output", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("tracks")
    op.drop_index("idx_progress_user_challenge", table_name="progress")
    op.drop_table("progress")
    op.add_column(
        "challenges", sa.Column("slug", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "challenges", sa.Column("track", sa.String(length=20), nullable=False)
    )
    op.add_column("challenges", sa.Column("validation_rules", sa.JSON(), nullable=True))
    op.add_column(
        "challenges", sa.Column("estimated_time", sa.Integer(), nullable=True)
    )
    op.add_column("challenges", sa.Column("starter_code", sa.Text(), nullable=True))
    op.add_column("challenges", sa.Column("solution_code", sa.Text(), nullable=True))
    op.add_column("challenges", sa.Column("resources", sa.JSON(), nullable=True))
    op.add_column("challenges", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column(
        "challenges",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "challenges",
        "difficulty",
        existing_type=postgresql.ENUM(
            "beginner", "intermediate", "advanced", name="challenge_difficulty"
        ),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "challenges",
        "requirements",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "challenges",
        "constraints",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "challenges",
        "test_config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "challenges",
        "points",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("100"),
    )
    op.alter_column(
        "challenges",
        "hints",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "challenges",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_index("idx_challenges_track_order", table_name="challenges")
    op.create_unique_constraint(None, "challenges", ["slug"])
    op.drop_constraint("challenges_track_id_fkey", "challenges", type_="foreignkey")
    op.drop_column("challenges", "model_tier")
    op.drop_column("challenges", "estimated_time_minutes")
    op.drop_column("challenges", "is_red_team")
    op.drop_column("challenges", "track_id")
    op.add_column(
        "conversations", sa.Column("title", sa.String(length=200), nullable=False)
    )
    op.alter_column(
        "conversations",
        "model_tier",
        existing_type=postgresql.ENUM("local", "haiku", "sonnet", name="model_tier"),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "conversations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_index("idx_conversations_user", table_name="conversations")
    op.drop_constraint(
        "conversations_user_id_fkey", "conversations", type_="foreignkey"
    )
    op.drop_constraint(
        "conversations_challenge_id_fkey", "conversations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "conversations", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("conversations", "messages")
    op.drop_column("conversations", "tokens_used")
    op.add_column(
        "submissions", sa.Column("status", sa.String(length=20), nullable=False)
    )
    op.add_column("submissions", sa.Column("passed", sa.Boolean(), nullable=False))
    op.add_column(
        "submissions", sa.Column("points_earned", sa.Integer(), nullable=False)
    )
    op.add_column(
        "submissions", sa.Column("completion_time", sa.Integer(), nullable=True)
    )
    op.add_column(
        "submissions",
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "submissions",
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("submissions", sa.Column("error_message", sa.Text(), nullable=True))
    op.add_column("submissions", sa.Column("feedback", sa.Text(), nullable=True))
    op.add_column("submissions", sa.Column("ai_requests", sa.Integer(), nullable=False))
    op.add_column("submissions", sa.Column("hints_used", sa.Integer(), nullable=False))
    op.alter_column(
        "submissions",
        "score",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "submissions",
        "test_results",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index("idx_submissions_user_challenge", table_name="submissions")
    op.drop_constraint(
        "submissions_challenge_id_fkey", "submissions", type_="foreignkey"
    )
    op.drop_constraint("submissions_user_id_fkey", "submissions", type_="foreignkey")
    op.create_foreign_key(
        None, "submissions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "submissions", "challenges", ["challenge_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("submissions", "created_at")
    op.alter_column(
        "users",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "tier",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'free'::user_tier"),
    )
    op.alter_column(
        "users",
        "tokens_used_today",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "users",
        "github_id",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "google_id",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "users",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_index("idx_users_email", table_name="users")
    op.create_unique_constraint(None, "users", ["google_id"])
    op.create_unique_constraint(None, "users", ["github_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "users",
        "is_verified",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "users",
        "google_id",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "github_id",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "tokens_used_today",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "users",
        "tier",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'free'::user_tier"),
    )
    op.alter_column(
        "users",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.add_column(
        "submissions",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "submissions", type_="foreignkey")
    op.drop_constraint(None, "submissions", type_="foreignkey")
    op.create_foreign_key(
        "submissions_user_id_fkey", "submissions", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "submissions_challenge_id_fkey",
        "submissions",
        "challenges",
        ["challenge_id"],
        ["id"],
    )
    op.create_index(
        "idx_submissions_user_challenge",
        "submissions",
        ["user_id", "challenge_id"],
        unique=False,
    )
    op.alter_column(
        "submissions",
        "test_results",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "submissions",
        "score",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.drop_column("submissions", "hints_used")
    op.drop_column("submissions", "ai_requests")
    op.drop_column("submissions", "feedback")
    op.drop_column("submissions", "error_message")
    op.drop_column("submissions", "completed_at")
    op.drop_column("submissions", "submitted_at")
    op.drop_column("submissions", "completion_time")
    op.drop_column("submissions", "points_earned")
    op.drop_column("submissions", "passed")
    op.drop_column("submissions", "status")
    op.add_column(
        "conversations",
        sa.Column(
            "tokens_used",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "conversations",
        sa.Column(
            "messages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "conversations", type_="foreignkey")
    op.create_foreign_key(
        "conversations_challenge_id_fkey",
        "conversations",
        "challenges",
        ["challenge_id"],
        ["id"],
    )
    op.create_foreign_key(
        "conversations_user_id_fkey", "conversations", "users", ["user_id"], ["id"]
    )
    op.create_index(
        "idx_conversations_user", "conversations", ["user_id"], unique=False
    )
    op.alter_column(
        "conversations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "conversations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "conversations",
        "model_tier",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM("local", "haiku", "sonnet", name="model_tier"),
        existing_nullable=False,
    )
    op.drop_column("conversations", "title")
    op.add_column(
        "challenges",
        sa.Column("track_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "challenges",
        sa.Column(
            "is_red_team",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "challenges",
        sa.Column(
            "estimated_time_minutes",
            sa.INTEGER(),
            server_default=sa.text("30"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "challenges",
        sa.Column(
            "model_tier",
            postgresql.ENUM("local", "haiku", "sonnet", name="model_tier"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "challenges_track_id_fkey", "challenges", "tracks", ["track_id"], ["id"]
    )
    op.drop_constraint(None, "challenges", type_="unique")
    op.create_index(
        "idx_challenges_track_order",
        "challenges",
        ["track_id", "order_index"],
        unique=False,
    )
    op.alter_column(
        "challenges",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "challenges",
        "hints",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "challenges",
        "points",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("100"),
    )
    op.alter_column(
        "challenges",
        "test_config",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "challenges",
        "constraints",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "challenges",
        "requirements",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "challenges",
        "difficulty",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM(
            "beginner", "intermediate", "advanced", name="challenge_difficulty"
        ),
        existing_nullable=False,
    )
    op.drop_column("challenges", "updated_at")
    op.drop_column("challenges", "is_active")
    op.drop_column("challenges", "resources")
    op.drop_column("challenges", "solution_code")
    op.drop_column("challenges", "starter_code")
    op.drop_column("challenges", "estimated_time")
    op.drop_column("challenges", "validation_rules")
    op.drop_column("challenges", "track")
    op.drop_column("challenges", "slug")
    op.create_table(
        "progress",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("challenge_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "not_started", "in_progress", "completed", name="progress_status"
            ),
            server_default=sa.text("'not_started'::progress_status"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "attempts",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "hints_used",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "best_score",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["challenge_id"], ["challenges.id"], name="progress_challenge_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="progress_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="progress_pkey"),
        sa.UniqueConstraint(
            "user_id", "challenge_id", name="progress_user_id_challenge_id_key"
        ),
    )
    op.create_index(
        "idx_progress_user_challenge",
        "progress",
        ["user_id", "challenge_id"],
        unique=False,
    )
    op.create_table(
        "tracks",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("order_index", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="tracks_pkey"),
    )
    op.drop_table("test_results")
    op.drop_table("payments")
    op.drop_table("conversation_messages")
    op.drop_table("user_progress")
    op.drop_table("token_usage")
    op.drop_table("subscriptions")
    op.drop_table("sessions")
    op.drop_table("certificates")
    op.drop_table("invoice_events")
    # ### end Alembic commands ###
